# **Deliverables for this week - From Github Repo**
## **Include:**

    1. Code that loads the HAM10000 metadata.
    2. A short explanation of the image_id, lesion_id, and dx columns.
    3. A table or chart showing the number of images in each class.
    4. Three observations about the dataset.
    5. A short explanation of why images sharing a lesion_id must remain in the same train, validation, or test split.

## **Task Division and Member Contribution**

    1. Two members load the CSV and explain its columns.
        * Devyani Lenin
        * Rishita Singh
    2. Two members produce and explain the class counts
        * Melanie Chappetta
        * Member 2
    3. One member writes the split explanation and checks that the notebook runs.
        * Yaden Gant
    4. Everyone adds an observation or explanation and reviews the shared output.

## **Important Notice**

    1. After any major changes, make sure to select File -> Save and Pin revision. This will help since multiple people will be working on this notebook.

# **1. Code that loads the CSV file**


1. Link to data: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DBW86T

2. I have shared a folder in Google drive with the required file path for everyone. If you run the cell below, it will ask you to 'Connect to Google Drive'. You can go ahead and connect,grant all permissions,  and you should be able to load the dataset.

3. Here is the link to the Google Drive for anyone in the project outside of our Group: https://drive.google.com/drive/folders/1gA-YqreIhWDNeQhykp4QWuSLDQbXYWuc?usp=sharing

4. **IF YOU GET AN ERROR WHEN LOADING FILE** ->  If it does not work, go to your Google drive and right click on the folder. You should see an 'Organize' option there, from which you can click on 'Add shortcut' and select the location as 'My Drive'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import os


file_path = (
    "/content/drive/MyDrive/"
    "PixelPathologyFall2026/data/raw/"
    "HAM10000/HAM10000_metadata.csv"
)


df = pd.read_csv(file_path)

print(f"Records: {len(df)}")
print(df.head())

Mounted at /content/drive
Records: 10015
     lesion_id      image_id   dx dx_type   age   sex localization  \
0  HAM_0000118  ISIC_0027419  bkl   histo  80.0  male        scalp
1  HAM_0000118  ISIC_0025030  bkl   histo  80.0  male        scalp
2  HAM_0002730  ISIC_0026769  bkl   histo  80.0  male        scalp
3  HAM_0002730  ISIC_0025661  bkl   histo  80.0  male        scalp
4  HAM_0001466  ISIC_0031633  bkl   histo  75.0  male          ear

        dataset
0  vidir_modern
1  vidir_modern
2  vidir_modern
3  vidir_modern
4  vidir_modern

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

 If you are getting an error uploading the file from Google Drive, you can run the cell below to find the exact file path.

In [ ]:
import os

search_root = '/content/drive/MyDrive'
target = 'HAM10000_metadata.csv'

matches = []

for root, dirs, files in os.walk(search_root):
    if target in files:
        matches.append(os.path.join(root, target))

print("Matching files found:", len(matches))

for path in matches:
    print(path)

Matching files found: 0

# **2. Short explanation of the image_id, lesion_id, and dx columns**



### **1.  image_id column**
        * The image_id column consists of 10015 records with a datatype of object.
        * These records are unique identifiers for individual skin images.
        * There records are in the format beggining with "ISIC_" and ending with a 7 digit number.
        * It serves as the primary key of the database, connecting data entries directly to image file names.
### **2. "lesion_id column**
        * The lesion_id column has 10015 records with the datatype object.
        * These records are unique identifiers for specific types of skin lesions.
        * It appears that multiple images can belong to the same lesion type.
        * It is formatted as HAM_00 followed by 5 digits
        * One lesion_id can correspond to multiple image_id entries because single lesions were often photographed at different angles or time points

### **3. "dx column**
        * The dx column has 10015 records with the datatype object,
        * These records are the diagnosis category assigned to that particular skin lesion.
        * It has 7 distinct classes - nv: melanocytic nevi(benign moles),
          mel: melanoma(malignant skin cancer),
          bkl: benign keratosis-like lesions(solar lentigines, seborrheic keratoses, lichen-planus-like keratoses),
          bcc: basil cell carcenoma (malignant),
          akiec: Actinic keratoses/intraepithelial carcinoma (pre-cancerous/bowen's disease),
          vasc: vascular lesions (angiomas, cherry angiomas, pyogenic granulomas, hemorrhage),
          dfb: dermatofibroma (benign skin lesion)
        * As shown below, bkl means benign keratosis-like lesions diagnosis.
        * This is a column the model can learn to predict.

In [ ]:
print(f'Number of Columns: {df.shape[1]}')

print("\nColumn Names:")
print(df.columns.tolist())

print("\nDataset Information:")
print(df.info())

print("\nFirst five rows of data:")
df.head(5)

Number of Columns: 8

Column Names:
['lesion_id', 'image_id', 'dx', 'dx_type', 'age', 'sex', 'localization', 'dataset']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10015 entries, 0 to 10014
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   lesion_id     10015 non-null  object
 1   image_id      10015 non-null  object
 2   dx            10015 non-null  object
 3   dx_type       10015 non-null  object
 4   age           9958 non-null   float64
 5   sex           10015 non-null  object
 6   localization  10015 non-null  object
 7   dataset       10015 non-null  object
dtypes: float64(1), object(7)
memory usage: 626.1+ KB
None

First five rows of data:

,lesion_id,image_id,dx,dx_type,age,sex,localization,dataset
0,HAM_0000118,ISIC_0027419,bkl,histo,80.0,male,scalp,vidir_modern
1,HAM_0000118,ISIC_0025030,bkl,histo,80.0,male,scalp,vidir_modern
2,HAM_0002730,ISIC_0026769,bkl,histo,80.0,male,scalp,vidir_modern
3,HAM_0002730,ISIC_0025661,bkl,histo,80.0,male,scalp,vidir_modern
4,HAM_0001466,ISIC_0031633,bkl,histo,75.0,male,ear,vidir_modern

# **Further Exploration of Columns Below:**

In [ ]:
target_cols = ['image_id', 'lesion_id', 'dx']
summary_df = pd.DataFrame({
    'Data Type': df[target_cols].dtypes,
    'Total Count': df[target_cols].count(),
    'Unique Values': df[target_cols].nunique(),
    'Missing Values': df[target_cols].isnull().sum()
})

print("=== Target Columns Summary ===")
print(summary_df)
print("\n" + "="*40 + "\n")

# 4. Multi-image lesion analysis
lesion_counts = df['lesion_id'].value_counts()
multi_image_lesions = (lesion_counts > 1).sum()
max_images = lesion_counts.max()

print("=== Lesion vs Image Breakdown ===")
print(f"Total Images (image_id): {df['image_id'].nunique()}")
print(f"Total Unique Lesions (lesion_id): {df['lesion_id'].nunique()}")
print(f"Lesions with multiple images: {multi_image_lesions} ({(multi_image_lesions/df['lesion_id'].nunique())*100:.1f}%)")
print(f"Max images recorded for a single lesion: {max_images}")
print("\n" + "="*40 + "\n")

# 5. Diagnostic class distribution (dx)
dx_mapping = {
    'nv': 'Melanocytic nevi',
    'mel': 'Melanoma',
    'bkl': 'Benign keratosis-like lesions',
    'bcc': 'Basal cell carcinoma',
    'akiec': 'Actinic keratoses',
    'vasc': 'Vascular lesions',
    'df': 'Dermatofibroma'
}

dx_summary = df['dx'].value_counts().reset_index()
dx_summary.columns = ['dx_code', 'image_count']
dx_summary['diagnosis_label'] = dx_summary['dx_code'].map(dx_mapping)
dx_summary['percentage'] = (dx_summary['image_count'] / len(df)) * 100

=== Target Columns Summary ===
          Data Type  Total Count  Unique Values  Missing Values
image_id     object        10015          10015               0
lesion_id    object        10015           7470               0
dx           object        10015              7               0

========================================

=== Lesion vs Image Breakdown ===
Total Images (image_id): 10015
Total Unique Lesions (lesion_id): 7470
Lesions with multiple images: 1956 (26.2%)
Max images recorded for a single lesion: 6

========================================

# **3. A table or chart showing the number of images in each class.**

In [ ]:
# Displayed image counts and percentages for each diagnosis
class_table = dx_summary[
    ['dx_code', 'diagnosis_label', 'image_count', 'percentage']
].copy()

class_table['percentage'] = class_table['percentage'].round(2)
display(class_table)

  dx_code                diagnosis_label  image_count  percentage
0      nv               Melanocytic nevi         6705       66.95
1     mel                       Melanoma         1113       11.11
2     bkl  Benign keratosis-like lesions         1099       10.97
3     bcc           Basal cell carcinoma          514        5.13
4   akiec              Actinic keratoses          327        3.27
5    vasc               Vascular lesions          142        1.42
6      df                 Dermatofibroma          115        1.15

### Class Count Explanation

This table summarizes the number of images in each of the seven diagnostic classes. Images were counted using the `dx` column, and each percentage was calculated by dividing the class count by the total of **10,015 images** and multiplying by 100. The classes are displayed from highest to lowest image count.

# **4. Three observations about the dataset.**

1. The dataset has 10,015 images, but the classes aren't evenly divided. The nv class has the most images, which could make it harder for the model to learn the smaller classes.

2. Some lesions have multiple images. Each image has a different image_id, but they can share the same lesion_id.

3. The dataset includes both benign and cancerous skin conditions. Some can look similar, so the model needs to learn how to tell them apart.

# **5. A short explanation of why images sharing a lesion_id must remain in the same train, validation, or test split.**
* Simpy put, as to make sure the model is able to generalize skin lesions across multiple patients. If the model is provided with the same patient/same legion at multiple different IDs, then it memorizes the things specific to that patient, like their skin texture, color or the kind of legion on them. If this is the case, then the model will be weaker at correctly identifying lesions on people that are unlike this one patient.